//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        public int Faktura_id { get; set; }
        public string Dostawca_id { get; set; }
        public string Odbiorca_id { get; set; }
        public int Pracownik_id { get; set; }
        public int Kaczka_id { get; set; }
        public int Ilosc { get; set; }
        public System.DateTime Data_wystawienia { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        public virtual Kaczki Kaczki { get; set; }
        public virtual Odbiorcy Odbiorcy { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
