//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int Uzytkownik_id { get; set; }
        public string Uzytkownik_nazwa { get; set; }
        public string Uzytkownik_haslo { get; set; }
        public string Rola { get; set; }
    }
}
